name: flutter_firebase_auth
description: A new Flutter project with Firebase authentication.
publish_to: 'none' # Remove this line if you want to publish to pub.dev

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
    flutter:
      sdk: flutter
    firebase_core: ^3.3.0
    firebase_auth: ^5.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
